name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PhpDocumentor
        uses: katrinaas/actions-phpDocumentor@v1
      - name: Save the changes
        uses: stefanzweifel/git-auto-commit-action@v4